# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', type: 'rsync'

  # libvirt.
  config.vm.define "libvirt" do |libvirt|
    libvirt.vm.hostname = "libvirt-debian11"
    libvirt.vm.box = "file://../builds/debian11-libvirt-VM.box"

    config.vm.provider :libvirt do |v|
      v.driver = "qemu"
      v.memory = 2048
    end
  end
end